name: Test workflow

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      # TODO: Change variable to your image's name.
      IMAGE_NAME: "cgerull/busybox"
      TAG: "latest"
    steps:
      - name:
        run: |
          echo "Do some templating"