name: Test versions

on:
  push:

jobs:
  push:
    runs-on: ubuntu-latest
    env:
      # TODO: Change variable to your image's name.
      IMAGE_NAME: "cgerull/busybox"
      TAG: "latest"
    steps:
      - name: Set image name and version
        run: |
          # Strip git ref prefix from version
          echo "ref ${{ github.ref }}"
          VER=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          echo "Get ref ${{ github.ref }}"
          # Strip "v" prefix from tag name
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VER=$(echo $VER | sed -e 's/^v//')
          echo "Strip leading v $VER"
          # Use Docker `latest` tag convention
          [[ $VER =~ [0-9].* ]] && echo "TAG=$VER" >> $GITHUB_ENV
          [[ $VER =~ [0-9].* ]] && echo "NEWTAG=$VER" >> $GITHUB_ENV
          echo VER $VER
          echo TAG ${{ env.TAG }}
          echo NEWTAG ${{ env.NEWTAG }}
          
          IMAGE="${{ env.IMAGE_NAME }}:${{ env.TAG }}"
          echo "IMAGE=$IMAGE" >> $GITHUB_ENV
          NEWIMAGE="${{ env.IMAGE_NAME }}:$VER"
          echo "NEWIMAGE=$NEWIMAGE" >> $GITHUB_ENV
      - name: Print image name env
        run: |
          echo "Image_NAME: ${{ env.IMAGE_NAME }}"
          echo "Tag: ${{ env.TAG }}"
          echo NEWTAG ${{ env.NEWTAG }}
          echo "IMAGE: ${{ env.IMAGE }}"
          echo "NEWIMAGE: ${{ env.NEWIMAGE }}"
